In [1]:
!pip install numpy

In [3]:
import numpy as np
a=np.array([1,2,3,4,"a"])
a

array(['1', '2', '3', '4', 'a'], dtype='<U21')

In [7]:
from contextlib import AbstractContextManager
a=np.array(10)
b=np.array([1,2,3])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
a

array(10)

In [8]:
b

array([1, 2, 3])

In [10]:
d

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [9]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [12]:
print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)

()
(3,)
(2, 3)
(2, 2, 3)


In [13]:
print(a.dtype)
print(b.dtype)
print(c.dtype)
print(d.dtype)

int64
int64
int64
int64


In [14]:
e=np.array([5,5.2,"abc"])
print(e.dtype)

<U32


In [15]:
print(type(a))
print(type(b))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [18]:
len(d)

2

In [17]:
len(b)

3

In [19]:
np.arange(1,11)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [23]:
np.eye(3,dtype='int')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [24]:
np.zeros((3,4),dtype='float')

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
np.zeros((4,3),dtype='int')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [28]:
np.ones((4,3),dtype='int')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [29]:
np.full((3,4),3,dtype='float')

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [30]:
x=[25,4,7,8,3]
np.diag(x)

array([[25,  0,  0,  0,  0],
       [ 0,  4,  0,  0,  0],
       [ 0,  0,  7,  0,  0],
       [ 0,  0,  0,  8,  0],
       [ 0,  0,  0,  0,  3]])

In [31]:
x=np.arange(1,17)
print(x)
print(x.shape)
print(x.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
(16,)
1


In [32]:
n=x.reshape((4,4))
print(n)
print(n.shape)
print(n.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
(4, 4)
2


In [33]:
n1=x.reshape((4,2,2))
print(n1)
print(n1.shape)
print(n1.ndim)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]]
(4, 2, 2)
3


In [34]:
v=n.ravel()
print(v.shape)
print(v)
print(v.ndim)

(16,)
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
1


In [35]:
n[0][1]=3
print(n)
print(v)

[[ 1  3  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[ 1  3  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [41]:
print(x)
r=x.reshape((2,4,2))
print(r)
x.flatten()


[ 1  3  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[[[ 1  3]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]]


array([ 1,  3,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [42]:
a=np.arange(2,17,2)
a

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [43]:
print(a[3])
print(a[7])

8
16


In [44]:
a[0:7:2]

array([ 2,  6, 10, 14])

In [45]:
a[1:4]

array([4, 6, 8])

In [48]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a[1,2])

6


In [49]:
print(a[2,0])

7


In [55]:
b=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(b.shape)
print(b)
print(b[1][0][1])

(2, 2, 3)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
8


In [58]:
print(a)
print(a[ : ,2])
print(a[ : ,1])
print(a[1: ,0])
print(a[0:3,1:3])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[3 6 9]
[2 5 8]
[4 7]
[[2 3]
 [5 6]
 [8 9]]


In [70]:
# 3D slicing:
b=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(b)
# print(b[0,1: ,1:3])
# print(b[0: , : ,1])
# print(b[1,1: , : ])
# print(b[0, 0:2 ,0:2])


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[1 2]
 [4 5]]


In [74]:
x1=np.arange(10)
x2=x1
print(x1)
print(x2)
x2[0]=5
print(x1)
print(x2)
print(id(x1))
print(id(x2))
print(np.shares_memory(x1,x2))

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[5 1 2 3 4 5 6 7 8 9]
[5 1 2 3 4 5 6 7 8 9]
139262328426192
139262328426192
True


In [80]:
x1=np.arange(1,10)
x3=x1.view()
print(x1)
print(x3)
print(id(x1))
print(id(x3))
np.shares_memory(x1,x3)

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
139262328438480
139262326016592


True

In [78]:
x3[0]=6
print(x1)
print(x3)
print(id(x1))
print(id(x3))
np.shares_memory(x1,x3)

[6 1 2 3 4 5 6 7 8 9]
[6 1 2 3 4 5 6 7 8 9]
139262328426192
139262328438480


True

In [91]:
x1=np.arange(1,10)
x1[0]=100
print(x1)
x4=np.copy(x1)
print(x4)
x4[2]=9
print(x4)
print(x1)
x1[3]=10
print(x1)
print(x4)
print(id(x1))
print(id(x4))
np.shares_memory(x1,x4)


[100   2   3   4   5   6   7   8   9]
[100   2   3   4   5   6   7   8   9]
[100   2   9   4   5   6   7   8   9]
[100   2   3   4   5   6   7   8   9]
[100   2   3  10   5   6   7   8   9]
[100   2   9   4   5   6   7   8   9]
139262326022544
139262326024272


False

In [93]:
print(a)
a>3

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [94]:
a[a>3]

array([4, 5, 6, 7, 8, 9])

In [96]:
a[(a>2) & (a<=7)]

array([3, 4, 5, 6, 7])

In [97]:
x1==x4

array([ True,  True, False, False,  True,  True,  True,  True,  True])

In [98]:
print(a.transpose())

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [99]:
x1=np.arange(1,5)
x2=np.arange(5,10)
np.hstack((x1,x2))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [103]:
x1=np.arange(1,6)
x2=np.arange(5,10)
print(x1)
print(x2)
np.vstack((x1,x2))

[1 2 3 4 5]
[5 6 7 8 9]


array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9]])

In [105]:
x1=np.arange(1,6)
x2=np.arange(5,10)
print(x1)
np.insert(x1,1,x2)

[1 2 3 4 5]


array([1, 5, 6, 7, 8, 9, 2, 3, 4, 5])

In [106]:
x1=np.arange(1,6)
print(x1)
np.insert(x1,3,[1,2,3])

[1 2 3 4 5]


array([1, 2, 3, 1, 2, 3, 4, 5])

In [107]:
x1=np.arange(1,6)
print(x1)
print(np.delete(x1,2))

[1 2 3 4 5]
[1 2 4 5]


In [109]:
a
np.sin(a)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849]])

In [113]:
np.sin(25)
np.cos(30)
np.tan(45)

np.float64(1.6197751905438615)

In [114]:
print((np.sin(a))/(np.cos(a)))

[[ 1.55740772 -2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501 -0.29100619]
 [ 0.87144798 -6.79971146 -0.45231566]]


In [115]:
print(np.exp(a))

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]


In [116]:
print(np.sum(a))

45


In [118]:
np.sum(a,axis=0)

array([12, 15, 18])

In [119]:
np.sum(a,axis=1)

array([ 6, 15, 24])

In [120]:
print(np.median(a))
print(np.mean(a))
print(np.std(a))
print(np.max(a))
print(np.min(a))
print(np.sort(x4))

5.0
5.0
2.581988897471611
9
1
[  2   4   5   6   7   8   9   9 100]


In [121]:
arr=np.array([[12,14,17,19,24,27,35,38]])
arr1=np.where(arr>17)
print(arr1)

(array([0, 0, 0, 0, 0]), array([3, 4, 5, 6, 7]))


In [124]:
print(dir(set))

['__and__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__iand__', '__init__', '__init_subclass__', '__ior__', '__isub__', '__iter__', '__ixor__', '__le__', '__len__', '__lt__', '__ne__', '__new__', '__or__', '__rand__', '__reduce__', '__reduce_ex__', '__repr__', '__ror__', '__rsub__', '__rxor__', '__setattr__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__xor__', 'add', 'clear', 'copy', 'difference', 'difference_update', 'discard', 'intersection', 'intersection_update', 'isdisjoint', 'issubset', 'issuperset', 'pop', 'remove', 'symmetric_difference', 'symmetric_difference_update', 'union', 'update']


In [126]:
import keyword
print(keyword.kwlist)
print(len(keyword.kwlist))

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']
35
